### ISSUE TITLE
Save() doesn't create a file with the original permissions

### ISSUE THREAD

**Issue by krultan** [AaronLenoir/flaclibsharp#35]
In Save(), the file is created in a temporary directory and then moved to the right place. In my case, the original file looses its 'Everyone read' permissions.

**Comment by AaronLenoir** [comment]
Thanks for taking the time to create this issue. 

That's a problem indeed, I'll look into it.

**Comment by AaronLenoir** [comment]
Hi krultan, I have release version 3.0.3 that fixes this. It should be available on NuGet by now.

I'm now using File.Copy to overwrite the original with the temp file, and then deleting the temp file. According to the File.Copy documentation: "The attributes of the original file are retained in the copied file. "

I have a test case as well that reproduced your issue, which 3.0.3 resolved.

Please re-open or create a new issue if you still have problems.
