### ISSUE TITLE
Expose VorbisComment.CueSheet property for FLAC embedded CueSheets

### ISSUE THREAD

**Issue by kborowinski** [AaronLenoir/flaclibsharp#48]
*Note: This's not to be confused with FLAC native CueSheet metadata field*

Many audio players (e.g. Foobar2000) allow for embedding album CueSheet in VorbisComment:

![image](https://user-images.githubusercontent.com/16168755/40922066-76e2a69c-6811-11e8-82bc-1d621e6748fa.png)

Currently to access CueSheet embedded in VorbisComment one has to access it through index of VorbisComment property.

Check following *PowerShell* code:
```powershell
> Add-Type -Path .\FlacLibSharp.dll
> $f = [FlacLibSharp.FlacFile]::new('C:\2004 - apparat - shapemodes.flac')
> $f.VorbisComment

Key                     Value
---                     -----
album                   {Test}
artist                  {Apparat}
cue_track01_TRACKNUMBER {01}
cue_track02_TRACKNUMBER {02}
cue_track03_TRACKNUMBER {03}
cue_track04_TRACKNUMBER {04}
cue_track05_TRACKNUMBER {05}
cue_track06_TRACKNUMBER {06}
cuesheet                {REM GENRE Electronic...
DATE                    {2004}
GENRE                   {Electronic}
LABEL                   {Neo Ouija}
STYLE                   {Glitch, Broken Beat, IDM, Experimental}
TOTALTRACKS             {06}

> $f.VorbisComment['cuesheet']
REM GENRE Electronic
REM DATE 2004
PERFORMER "Apparat"
TITLE "Shapemodes"
REM REPLAYGAIN_ALBUM_GAIN -1.92 dB
REM REPLAYGAIN_ALBUM_PEAK 0.977234
FILE "2004 - apparat - shapemodes.flac" WAVE
  TRACK 01 AUDIO
    TITLE "Solaris"
    REM REPLAYGAIN_TRACK_GAIN -1.83 dB
    REM REPLAYGAIN_TRACK_PEAK 0.951843
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Riding"
    REM REPLAYGAIN_TRACK_GAIN +4.00 dB
    REM REPLAYGAIN_TRACK_PEAK 0.977234
    INDEX 01 06:08:69
  TRACK 03 AUDIO
    TITLE "Get Out Of Your Krib"
    REM REPLAYGAIN_TRACK_GAIN -1.28 dB
    REM REPLAYGAIN_TRACK_PEAK 0.977234
    INDEX 01 10:34:66
  TRACK 04 AUDIO
    TITLE "Scissors And Saxophones"
    REM REPLAYGAIN_TRACK_GAIN -4.99 dB
    REM REPLAYGAIN_TRACK_PEAK 0.939636
    INDEX 01 14:48:23
  TRACK 05 AUDIO
    TITLE "Sinus"
    REM REPLAYGAIN_TRACK_GAIN -1.82 dB
    REM REPLAYGAIN_TRACK_PEAK 0.931366
    INDEX 01 18:59:66
  TRACK 06 AUDIO
    TITLE "Radau"
    REM REPLAYGAIN_TRACK_GAIN -1.89 dB
    REM REPLAYGAIN_TRACK_PEAK 0.977203
    INDEX 01 25:40:37
```

*Proposal:*

Add CueSheet property to VorbisComment so it can be accessed directly:
```powershell
> $f.VorbisComment.CueSheet
```

**Comment by AaronLenoir** [comment]
What's the format of this Cuesheet data in the tag? Do you have some good resources? I think I may be missing it, but I can't find a good reference for this format.

I'd love to get it implemented. I'll see when I find some time.

Thanks for the suggestion! I really appreciate it! Really cool you're using it from PowerShell, hadn't even thought of that.

**Comment by kborowinski** [comment]
@AaronLenoir As for the CueSheet data format you could check, [hydrogenaudio wiki.](https://wiki.hydrogenaud.io/index.php?title=Cue_sheet) However in my example you can see that *Foobar2000* keeps *ReplayGain* info in comments. The problem with CueSheet format is that there's a lots of apps that diverge from the *standard*. So instead of processing CueSheet data (which would be amazing but may be hard to cover all the edge cases) what I was looking for is rather simple addition of extra *VorbisCommenValue* e.g:

```c#
        /// <summary>
        /// Gets or sets the embedded CueSheet if available.
        /// </summary>
        /// <remarks>If not found an empty string is returned.</remarks>
        public VorbisCommentValues CueSheet {
            get { return this["CUESHEET"]; }
            set { this["CUESHEET"] = value; }
        }
```
In fact it would be great, if you'd implement import and export of embedded CueSheet to file (with UTF8 encoding). The same for pictures. But this's not as important because I can do it with *PowerShell* and your amazing *FlacLibSharp* already.

**Comment by AaronLenoir** [comment]
Oh I see what you mean! Yeah that would be a small addition, can be done for sure.

I agree parsing it if there's no real standard is probably a rabbit hole I can't get into at the moment.

**Comment by AaronLenoir** [comment]
@kborowinski it's in the master branch now and it'll be in [version 3.2.0](https://github.com/AaronLenoir/flaclibsharp/milestone/6)
