### ISSUE TITLE
Need a method to add a new cover or replace old cover

### ISSUE THREAD

**Issue by SofiaXu** [AaronLenoir/flaclibsharp#53]

**Comment by AaronLenoir** [comment]
Hello, thanks for your interest! I may need some more information, as I was under the impression I covered everything available in FLAC metadata and ID3 tags.

It should be possible to add a PICTURE metadata block, with the type set to Cover (front) (`PictureType.CoverFront`).

Is this not working, or is the question more to have a more straight forward API call around it?

You can assign a picture as a URL, or a picture with binary data (in the form of a byte array). You can see an example in one of the Unit Tests: [FlacLibSharp.Test.Core.WriteTests.cs:444](https://github.com/AaronLenoir/flaclibsharp/blob/master/FlacLibSharp.Test.Core/WriteTests.cs#L444)
```
Picture pict = null;

pict = new FlacLibSharp.Picture();
pict.ColorDepth = 24;
pict.Data = imageData;
pict.Description = "Small picture test ...";
pict.Height = 420;
pict.Width = 410;
pict.MIMEType = "image/png";
pict.PictureType = PictureType.CoverFront;

flac.Metadata.Add(pict);

pict = new FlacLibSharp.Picture();
pict.ColorDepth = 24;
pict.Description = "Small URL picture test ...";
pict.Height = 768;
pict.Width = 1024;
pict.MIMEType = "-->";
pict.PictureType = PictureType.CoverFront;
pict.URL = "http://38.media.tumblr.com/0e954b0469c281a9a09eb1378daada3e/tumblr_mh0cpm19zR1s3yrubo1_1280.jpg";
```

**Comment by SofiaXu** [comment]
Hi, I see. I'm writing a program to resize Cover (front) because some BitTorrent sites need file size of cover less than 512 KiB. I have used code like you provided.
` int pictureDataIndex = flacFile.Metadata.IndexOf(flacFile.Metadata.Find(match => match.Header.Type == MetadataBlockHeader.MetadataBlockType.Picture));
((Picture)flacFile.Metadata[pictureDataIndex]).Data = File.ReadAllBytes(resizedCoverName.ToString());
((Picture)flacFile.Metadata[pictureDataIndex]).Width /= 2;
((Picture)flacFile.Metadata[pictureDataIndex]).Height /= 2;
flacFile.Save();`
But I don't know what property Colors mean. Also, I think can add an method(function) into FastFlac.cs that can use Bitmap object replace old Cover (front) or add new one.

**Comment by AaronLenoir** [comment]
Hello

For my understanding: is this something that you are _unable_ to do or something you are _able_ to do, but not as easily as you would like?

The "Colors" property only applies to "indexed-colour" images, such as "gif". For other images (like jpeg), this property can be 0.

From the FLAC specification: 

> For indexed-color pictures (e.g. GIF), the number of colors used, or 0 for non-indexed pictures.
>
> See: https://xiph.org/flac/format.html#metadata_block_picture

 I can see some potential in the Picture class accepting a `Bitmap` and setting the Width and Height according to the image. But then, I guess, I would need to convert it to JPEG or PNG because I wouldn't want to store an actual bitmap image in the metadata.

**Comment by SofiaXu** [comment]
Hi, Thanks for your reply, I have understood it.
