### ISSUE TITLE
Error reading some flac files

### ISSUE THREAD

**Issue by pkfox** [AaronLenoir/flaclibsharp#54]
Hi Aaron , thanks for the great library -  I'm seeing this exception when opening certain ( not all ) flac files.
It is thrown here which is in BinaryDataHelper.cs

public static UInt64 GetUInt64(byte[] data, int byteOffset, int bitCount, byte bitOffset) 

Specified argument was out of the range of valid values.
Parameter name: Provided arguments would require reading outside of the data array upper bounds

**Comment by AaronLenoir** [comment]
Hello @pkfox sorry I didn't see your post sooner.

Could you share one or more of the files that are failling. The GetUInt64 function is a generic function, so from that it's hard to say what part of the file the library is having issues with. If you can't provide the file, are you able to get the full stack trace of the exception?

Thanks for the help!

**Comment by pkfox** [comment]
[Nocturne No 1 in B flat minor Op 9 No 1.zip](https://github.com/AaronLenoir/flaclibsharp/files/5601136/Nocturne.No.1.in.B.flat.minor.Op.9.No.1.zip)

Hi Aaron thanks for getting back to me - having done some research I think the problem stems from the fact that, I have a lot of flac files that don't have the magic marker fLaC in the header , they were ripped a long time ago by a Linux program called Grip. As you can see the in the file I've supplied the magic marker is ID3 so it failed the VerifyFlacIdentity() in FlacFile.cs. To progress further into the program I commented out the call to VerifyFlacIdentity() and then got the error I reported. Hope that helps.

**Comment by AaronLenoir** [comment]
Thanks!

The problem doesn't seem to be that it doesn't have a fLaC marker. It's actually there a little further, but it looks like a big blob of ID3 metadata is put in front of it. By itself that's a little weird because the FLAC format has a place for ID3 data.

Since `metaflac` has no issues with your file, I think they are ignoring all bytes before the magic marker, where FlacLibSharp just bails out if the file doesn't start with that marker. I think I can do the same.

**Comment by AaronLenoir** [comment]
@pkfox I think I covered that case now, if you have some time could you try it out with this branch on some of your files and let me know how it goes? 

- https://github.com/AaronLenoir/flaclibsharp/tree/bug/issue-54

**Comment by pkfox** [comment]
Hi Aaron  all is good now - thanks very much

**Comment by AaronLenoir** [comment]
Good news! I'll make a release.

Thanks a lot for taking the time to report the issue, this made the library more useful!

**Comment by AaronLenoir** [comment]
The fix is in the newly published release version 3.2.1
