### ISSUE TITLE
Is there a way to add custom tag names?

### ISSUE THREAD

**Issue by Syco54645** [AaronLenoir/flaclibsharp#56]
I have some flac that has more metadata than the supported by this library, is there a way to access/add custom metadata tags? Looking for DISCNUMBER, COMMENT, and YEAR.

**Comment by Syco54645** [comment]
I found how to do this by poking around at the library.

**Comment by AaronLenoir** [comment]
Good to hear. You were talking about custom Vorbis Comment tags?

I think it's like this, is it?

```
using (FlacFile file = new FlacFile("Some File.flac"))
{
  var vorbisComment = new VorbisComment();
  vorbisComment["SOME_TAG"] = new VorbisCommentValues("Some Value");
  file.Metadata.Add(vorbisComment);
  file.Save();
}
```
